# Generated by Django 5.1.7 on 2025-03-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='quantity',
            new_name='ingridients_quantity',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingridients',
        ),
    ]
