# Generated by Django 5.1.7 on 2025-03-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_quantity_reciperequirement_ingridients_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
    ]
