# Generated by Django 5.1.7 on 2025-03-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_ingridient_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='ingridients_quantity',
            new_name='ingredients_quantity',
        ),
    ]
