# Generated by Django 5.1.7 on 2025-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_ingridients_quantity_reciperequirement_ingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='menu_items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredients_quantity',
            field=models.JSONField(),
        ),
    ]
